### ISSUE TITLE
Enable Loki on monitoring.scs.community

### ISSUE THREAD

**Issue by jschoone** [SovereignCloudStack/k8s-observability#50]
As an SCS Operator I want to expose my Kubernetes logs to a Prometheus, so I can make this logs accessible without giving permissions in my Kubernetes clusters.

In SCS we now have a specific case with the shared Kubernetes clusters. For example we want to give users permissions to test Cluster Stacks on it without giving them access to the CSO/CSPO-Resources directly on the cluster. But since they need/want to now what's wrong if the cluster doesn't come up, they can check the logs on monitoring.scs.community.

**Comment by matofeder** [comment]
dNation monitoring needed some Loki related updates.
- The Loki helm chart source has changed to [grafana/loki](https://github.com/grafana/loki/tree/main/production/helm/loki)
- The Loki-distributed helm chart has been deprecated and replaced by the [grafana/loki](https://github.com/grafana/loki/tree/main/production/helm/loki)
- The promtail helm chart version and Loki helm chart version have been bumped
- The CI pipeline has been updated
- Helm values have been re-structured and documented better

See https://github.com/dNationCloud/kubernetes-monitoring-stack/pull/100

**Comment by matofeder** [comment]
Loki was deployed at https://monitoring.scs.community/ last night along with the Promtail agent on each Observer node.

This setup ensures that the SCS Observer platform collects logs from itself and can also serve as a global, horizontally scalable, highly available, multi-tenant log aggregation system.

Now we are able so see logs and metrics from observer cluster side-by side, e.g. see some container logs and metrics [here](https://monitoring.scs.community/d/containerdetail/container-detail?var-container=etcd&var-namespace=kube-system&var-pod=All&var-view=container&var-search=&refresh=10s&var-datasource=PC96415006F908B67&var-cluster=observer-cluster&from=now-30m&to=now&orgId=1&var-datasource_logs=P8DEED8F9F62C80CB&var-instance=All)
or via the grafana explore https://monitoring.scs.community/explore

Find en example helm values in [values-observer-scs.yaml](https://github.com/SovereignCloudStack/k8s-observability/blob/main/values-observer-scs.yaml#L130). 

Contact @dnation folks for productive values used for SCS instance deployment available at monitoring.scs.community.

Loki API endpoint for logs ingestion is available at [monitoring.scs.community/loki](http://monitoring.scs.community/loki).
Basicauth is used here, contact @dnation folks for user/pass info.

**Comment by matofeder** [comment]
Several follow-up issues have been opened:
    - Enhance Authentication for Loki API Endpoint - https://github.com/SovereignCloudStack/k8s-observability/issues/61
    - Enable Loki deployment by default - https://github.com/SovereignCloudStack/k8s-observability/issues/59
    - Enable Promtail Agents in the "SCS Harbor Cluster" - https://github.com/SovereignCloudStack/k8s-observability/issues/62
    - Enable grafana explore feature for the anonymous access - https://github.com/SovereignCloudStack/k8s-observability/issues/63
    - Improve docs - https://github.com/SovereignCloudStack/k8s-observability/issues/60
