### ISSUE TITLE
Enable Promtail Agents in the "SCS Harbor Cluster" and configure them to send cluster logs to the SCS Observer's Loki instance

### ISSUE THREAD

**Issue by matofeder** [SovereignCloudStack/k8s-observability#62]
As an SCS Operator, I want to see "SCS Harbor Cluster"  logs in the SCS monitoring platform and have a global view for both metrics and logs.

**Comment by michal-gubricky** [comment]
Fixed via [PR#71](https://github.com/SovereignCloudStack/k8s-observability/pull/71)
