### ISSUE TITLE
Enable grafana explore feature for the anonymous access

### ISSUE THREAD

**Issue by chess-knight** [SovereignCloudStack/k8s-observability#63]
This project uses `GF_AUTH_ANONYMOUS_ENABLED=true` env variable for the grafana to allow anonymous users to view SCS monitoring metrics and logs.
We also want to grant access to grafana explore feature for the viewers.

One way how to do it is to use [viewers_can_edit](https://grafana.com/docs/grafana/latest/setup-grafana/configure-grafana/#viewers_can_edit) setting. In our case, set `GF_USERS_VIEWERS_CAN_EDIT=true`

**Comment by michal-gubricky** [comment]
After adding this env variable `GF_USERS_VIEWERS_CAN_EDIT: true` into values, anonymous users are able to view logs. But also they can now edit dashboards, etc. and I think this is not what we want.

**Comment by chess-knight** [comment]
> After adding this env variable `GF_USERS_VIEWERS_CAN_EDIT: true` into values, anonymous users are able to view logs. But also they can now edit dashboards, etc. and I think this is not what we want.

Users can edit panels and queries but are not able to save them or create new dashboards.

**Comment by michal-gubricky** [comment]
> > After adding this env variable `GF_USERS_VIEWERS_CAN_EDIT: true` into values, anonymous users are able to view logs. But also they can now edit dashboards, etc. and I think this is not what we want.
> 
> Users can edit panels and queries but are not able to save them or create new dashboards.

Yes, after testing it, users can only hit `apply` button. For saving, they need to have additional permissions.
